#TODO: move sensitive data to .env
server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: app_user
    password: app_pass
    hikari:
      auto-commit: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include:
            - health
            - refresh

frontend:
  base_url: "http://localhost:3000"

app:
  base_url: "http://localhost:8081"
  oidc:
    defaults:
      defaultName: User

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

auth:
  jwk-set-endpoint: /.well-known/jwks.json
  issuer-uri: http://localhost:8081
