server:
  port: 8080

spring:
  application:
    name: Video Platform Gateway Service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/oauth2/**, /login, /logout, /api/auth/**

        - id: upload-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/upload/**
          filters:
            - name: JwtHeaderFilter

        - id: metadata-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/metadata/**
          filters:
            - name: JwtHeaderFilter

        - id: streaming-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/streaming/**
          filters:
            - name: JwtHeaderFilter

        - id: encoding-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/encoding/**
          filters:
            - name: JwtHeaderFilter

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
          issuer-uri: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
          - gateway
  endpoint:
    gateway:
      enabled: true
